project_blog/blog/urls.py
from django.urls import path

#from blog.views import PostListView
from blog.feeds import LatestPostFeed
from blog.views import post_list, post_detail, post_share, post_search

app_name = 'blog'
urlpatterns = [
    #path('', PostListView.as_view(), name='post_list'),
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', post_search, name='post_search'),

]

project_blog/project_blog/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

project_blog/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """Пользовательский менеджер"""

    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    """Модель статей"""
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    status_choices = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        to=User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
    body = models.TextField(verbose_name='Текст')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')
    status = models.CharField(
        max_length=10, choices=status_choices, default='draft', verbose_name='Статус')

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Модель комментариев"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Статья')
    name = models.CharField(max_length=80, verbose_name='Автор')
    email = models.EmailField(verbose_name='e-mail')
    body = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='отредактирован')
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return 'Комментарий {} на статью {}'.format(self.name, self.post)

project_blog/blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    """Форма для отправки статьи по e-mail"""
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """Форма для добавления комментария"""

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)


class SearchForm(forms.Form):
    """Форма поиска"""
    query = forms.CharField()

project_blog/blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
# from django.views.generic import ListView
from taggit.models import Tag

from blog.forms import EmailPostForm, CommentForm, SearchForm
from blog.models import Post


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    """получение списка статей"""
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    """получение информации о статье"""
    post = get_object_or_404(
        Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments,
                                                     'new_comment': new_comment, 'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    """поделиться статьей"""
    # получение статьи по id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        # валидация формы
        if form.is_valid():
            cd = form.cleaned_data
            # отправка почты
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) Рекомендовано Вам для чтения "{}"'. \
                format(cd['name'], cd['email'], post.title)
            message = 'Читайте "{}" в {}\n\n{} комментарии: {}'. \
                format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@blog.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    """поиск"""
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            search_rank = SearchRank(search_vector, search_query)
            results = Post.objects.annotate(search=search_vector, rank=search_rank).\
                filter(rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})

project_blog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>Блог</h2>
        <p>На данный момент написано {% total_posts %} статей</p>
        <p><a href="{% url 'blog:post_feed' %}">Подпишитесь на RSS-рассылку</a></p>
        <h3>Последние сообщения</h3>
        {% show_latest_posts 3 %}
        <h3>Наибольшее количество комментариев у статей: </h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

project_blog/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Назад</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Вперед</a>
        {% endif %}
    </span>
</div>

project_blog/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Опубликована {{ post.publish }} {{post.author}}</p>
    {{ post.body | linebreaks }}
    <p><a href="{% url 'blog:post_share' post.id %}">Поделиться этим сообщением</a></p>
    <p>Рекомендуемые статьи</p>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
        {% empty %} Рекомендованных статей нет.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} комментария</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }}, автор: {{ comment.name }}, создан {{ comment.created}}
            </p>
            {{ comment.body | linebreaks }}
        </div>
    {% empty %}
        <p>Комментариев пока нет</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Ваш комментарий был добавлен</h2>
    {% else %}
        <h2>Добавить новый комментарий</h2>
        <form action="." method="POST">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}
{% endblock %}

project_blog/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>

project_blog/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}Блог{% endblock %}
{% block content %}
    <h1>Блог</h1>
    {% if tag %}
        <h2>Сообщения помечены как "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            Теги:
            {%for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Опубликовано {{ post.publish }} {{ post.author }}</p>
        {{ post.body | truncatewords:30 | linebreaks }}
    {% endfor %}
    {% include 'blog/pagination.html' with page=posts %}
{% endblock %}

project_blog/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% block title %}Поиск{% endblock %}
{% block content %}
    {% if query %}
        <h1>Сообщения содержащие "{{ query }}":</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено {{ total_results }} статей
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body | truncatewords:5 }}<br><br><br>
        {% empty %}
            <p>Нет статей по Вашему запросу</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Новый поиск</a></p>
    {% else %}
        <h1>Поиск статей</h1>
        <form action="." method="get">
            {{form.as_p}}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

project_blog/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Поделиться статьей{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлен</h1>
        <p>"{{ post.title }}" был отправлен в адрес {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Поделиться статьей "{{ post.title }}" через e-mail</h1>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправка email">
        </form>
    {% endif %}
{% endblock%}